apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_PORT
          value: "5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio.mlops-storage.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        - name: MLFLOW_DISABLE_DNS_REBINDING_PROTECTION
          value: "true"
        command:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=sqlite:///mlflow.db
        - --default-artifact-root=s3://mlflow-artifacts/
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops-tracking
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
